### ISSUE TITLE
Exception useCuda = true

### ISSUE THREAD

**Issue by nckoff** [ivilson/Yolov7net#6]
If i choose useCuda = True

Microsoft.ML.OnnxRuntime 1.11.0:
![0688_688_2022_12_10_Vision_v1pMV1d0Af](https://user-images.githubusercontent.com/92748912/206864106-0ad4d807-61f5-4458-b299-b14e49aa3bb5.jpg)

I thought I needed Microsoft.ML.OnnxRuntime.Gpu
Microsoft.ML.OnnxRuntime.Gpu 1.11.0:
![0689_689_2022_12_10_Vision_GtZk2jFSA8](https://user-images.githubusercontent.com/92748912/206864207-66f509f3-c7c0-4d5b-97de-cfaa827dac2b.jpg)

Microsoft.ML.OnnxRuntime.Gpu 1.13.1:
![0690_690_2022_12_10_Vision_TlLTUM39Vu](https://user-images.githubusercontent.com/92748912/206864248-ef98e954-ad39-4ec9-b6ca-c5dbc42f21fa.jpg)

I tried on different devices Windows 10/11
Please, help.

**Comment by mikelmujika11** [comment]
Hi @nckoff,

Have you solved the issue? Because I am facing the same problem.

Thanks,

**Comment by iwaitu** [comment]
Have you installed the cuda library on your Windows platform and successfully run the Nvidia sample code?

**Comment by mikelmujika11** [comment]
Hi @iwaitu,

I installed cuda from this link: https://developer.nvidia.com/cuda-downloads.
Where can I found the Nvidia sample code?

Thanks,

**Comment by iwaitu** [comment]
https://www.youtube.com/watch?v=cL05xtTocmY

**Comment by mikelmujika11** [comment]
I have followed the video and I have run the examples correctly, but the program still gives me the same error.

**Comment by iwaitu** [comment]
Where the weight file come from? Maybe you should try to export your own onnx file by use your custom pt file.

**Comment by mikelmujika11** [comment]
Hi @iwaitu ,

The weights are custom weights. I have obtained a .pt first and transformed to .onnx to use it with c#. The problem is that set useCuda = False the program works. But it uses the CPU so it is really slow. That's why I want to use the GPU, setting the useCuda = True, but it gives me the error.

**Comment by iwaitu** [comment]
the problem is your export params, before you export your  onnx file,you should try this:

```
model.cuda()
mode.eval()
```

**Comment by zzzdddyyy** [comment]
Have you downloaded and configured [cuDNN](https://developer.nvidia.com/cudnn)?

**Comment by AVISIX** [comment]
> If i choose useCuda = True
> 
> Microsoft.ML.OnnxRuntime 1.11.0: ![0688_688_2022_12_10_Vision_v1pMV1d0Af](https://user-images.githubusercontent.com/92748912/206864106-0ad4d807-61f5-4458-b299-b14e49aa3bb5.jpg)
> 
> I thought I needed Microsoft.ML.OnnxRuntime.Gpu Microsoft.ML.OnnxRuntime.Gpu 1.11.0: ![0689_689_2022_12_10_Vision_GtZk2jFSA8](https://user-images.githubusercontent.com/92748912/206864207-66f509f3-c7c0-4d5b-97de-cfaa827dac2b.jpg)
> 
> Microsoft.ML.OnnxRuntime.Gpu 1.13.1: ![0690_690_2022_12_10_Vision_TlLTUM39Vu](https://user-images.githubusercontent.com/92748912/206864248-ef98e954-ad39-4ec9-b6ca-c5dbc42f21fa.jpg)
> 
> I tried on different devices Windows 10/11 Please, help.

Hey there, I had the exact same issue. This is because you either don't have CUDA and CudNN not installed or the PATH environment variable doesn't have the paths of the CUDA and CudNN binaries.

I have manually added the required files to my project. For me it looks like this:
![image](https://github.com/ivilson/Yolov7net/assets/54699751/04f091bf-c92b-4d1f-9521-24559307c65a)

Depending on the version, you might need different files.

**Comment by iwaitu** [comment]
If you have successfully exported the ONNX file and correctly installed CUDA and cuDNN, then you need to add Microsoft.ML.OnnxRuntime.Gpu to your project.
